# Generated by Django 4.1.4 on 2022-12-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
            options={
                'verbose_name': 'Kategorii',
                'verbose_name_plural': 'kategoriya',
            },
        ),
    ]
